stages:
    - test

.test_dependencies: &test_dependencies
    - |
        set -eux

        apt-get -y update
        apt-get -y upgrade
        apt-get -y --no-install-recommends install \
        meson \
        python3 \
        python3-flask \
        python3-semantic-version \
        ${NULL+}

.test_template:
    stage: test
    tags:
        - docker
        - linux

test:debian-10:
    extends: .test_template
    image: debian:buster-slim
    script:
        - *test_dependencies
        - |
            set -eux

            meson _build/tests
            ninja -C _build/tests
            meson test --verbose -C _build/tests

    artifacts:
        paths:
            - _build/tests/meson-logs/*.txt
        when: always

test:debian-11:
    extends: .test_template
    image: debian:bullseye-slim
    script:
        - *test_dependencies
        - |
            set -eux

            meson _build/tests
            ninja -C _build/tests
            meson test --verbose -C _build/tests

    artifacts:
        paths:
            - _build/tests/meson-logs/*.txt
        when: always
