[Server]
# Default hostname
#Host = locahost
# Port
#Port = 5000

[Images]
# The directory where images are stored
PoolDir = ./examples-data/images/releases
# Name of supported product
Product = steamos
# Name of supported release
Release = holo
# List of variants, separated with a space
Variants = steamdeck steamdeck-test1 testfoo
# List of end-of-life variants. The syntax is: which variant reached EOL, followed by a colon
# and the replacement variant that should be followed instead. To list multiple EOL variants
# you can separate them with a space
VariantsEOL = steamdeck-test1:steamdeck testfoo:steamdeck
# List of branches, separated with a space
Branches = stable beta rc staging
# List of architectures, separated with a space
Archs = amd64
# Whether to perform additional checks to validate the image pool
# For example the server will exit with an error in case there isn't at least
# one image for every branch listed in "Branches".
# If this field is missing, it will be set by default to True.
StrictPoolValidation = False

[Images.BranchesToConsider]
# Optional lists of more stable branches that should be considered when looking for updates
#
# When requesting an update for a specific branch, the server will also
# consider the branches that are more stable than the requested one as
# possible candidates. The order of the lists is irrelevant.
#
# Note: Every "Branches" entry is not required here. For example for the
# "stable" branch you may not want to consider other branches
beta = rc stable
rc = stable

[Images.ProvideRemoteInfoConfig.amd64]
# Optional list of variants and branches to create the "remote-info.conf" files.
# This is used to provide a more up-to-date list of known variants and branches to the clients.
#
# Not providing this section will prevent the "remote-info.conf" files to be created.
#
# If you list EOL variants here, they will be automatically excluded when generating the remote
# info file for the other, non EOL, variants.
# E.g. in this example `/steamdeck-test1/remote-info.conf` will have both variants, while `/steamdeck/remote-info.conf`
# will just have `steamdeck`
Variants = steamdeck steamdeck-test1
Branches = stable beta rc

[LightweightCheckpoint.steamdeck.1]
# Clients that want to go to these branches, must update to the target checkpoint first, unless they meet the
# prerequisites listed in the ExemptFrom variable. In that case they don't need the target checkpoint.
# ExemptFrom defines minimum version/build combinations that bypass this checkpoint.
# A client is exempt if it satisfies ANY of the listed conditions. Minor versions newer than those
# listed, are assumed to satisfy the requirement.
# If there are no ExemptFrom listed, this lightweight checkpoints becomes mandatory for everyone.
Targets = main:3.8:20251119.1000
# This one means:
# - If an image is in the 3.7.x version, it must be at least 3.7.16 and with buildid 20251105.0 or greater
# - If an image is in the 3.8.x version, it must have a buildid of 20251119.1000 or greater
# - If the version is 3.9.x or newer, it always satisfies the prerequisites
# - If the version is 3.6.x or older, it doesn't
ExemptFrom = 3.7.16:20251105.0 3.8:20251119.1000

[LightweightCheckpoint.steamdeck.2]
# In this example, if the client is already in a 3.9.0 version, and with a buildid of at least
# 20260103.1000, it can skip this lightweight checkpoint.
# If there was no 3.9.x entry in ExemptFrom, then ALL 3.9.x images would have been considered
# exempt by default.
Targets = main:3.9:20260215.1000
ExemptFrom = 3.8.2:20260222.1 3.9:20260103.1000
